# Generated by Django 5.2 on 2025-04-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_artikel_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='isi',
            new_name='speksifikasi',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='author',
        ),
    ]
