# Generated by Django 5.2 on 2025-04-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_rename_isi_artikel_speksifikasi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='judul',
            new_name='nama',
        ),
    ]
