# Generated by Django 5.2 on 2025-05-04 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_rename_judul_artikel_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
