# Generated by Django 5.2 on 2025-04-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_data_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': '1. Data'},
        ),
    ]
